Repository Laixer/FunderMaps, pull requests merged in 2020-09, with the labels that each got.

#252 Anonymous and user-based incident reports
  .github/workflows/dotnet-core.yml
  src/FunderMaps.WebApi/Controllers/Report/IncidentController.cs
  src/FunderMaps.WebApi/DataTransferObjects/IncidentDTO.cs
  tests/FunderMaps.IntegrationTests/Backend/Report/IncidentAnonymousTests.cs
  tests/FunderMaps.IntegrationTests/Faker/IncidentDtoFaker.cs
Labels: Feature

#267 Feature/systemd
  .github/workflows/dotnet-core-package-outdated.yml
  src/FunderMaps.AspNetCore/FunderMaps.AspNetCore.csproj
  src/FunderMaps.Core.Authentication/FunderMaps.Core.Authentication.csproj
  src/FunderMaps.Core/FunderMaps.Core.csproj
  src/FunderMaps.Infrastructure/FunderMaps.Infrastructure.csproj
  src/FunderMaps.WebApi/FunderMaps.WebApi.csproj
  src/FunderMaps.WebApi/Program.cs
  src/FunderMaps.Webservice/FunderMaps.Webservice.csproj
  src/FunderMaps.Webservice/Program.cs
  tests/FunderMaps.IntegrationTests/FunderMaps.IntegrationTests.csproj
  tests/FunderMaps.Webservice.UnitTests/FunderMaps.Webservice.UnitTests.csproj
Labels: Feature, enhancement

#273 Remove IncidentEndpoint Azure Function
  FunderMaps.sln
  src/FunderMaps.IndicentEndpoint/.gitignore
  src/FunderMaps.IndicentEndpoint/Extensions/HttpRequestExtensions.cs
  src/FunderMaps.IndicentEndpoint/Extensions/IncidentExtensions.cs
  src/FunderMaps.IndicentEndpoint/FunderMaps.IndicentEndpoint.csproj
  src/FunderMaps.IndicentEndpoint/GlobalSuppressions.cs
  src/FunderMaps.IndicentEndpoint/HttpPortalEndpoint.cs
  src/FunderMaps.IndicentEndpoint/Startup.cs
  src/FunderMaps.IndicentEndpoint/ViewModels/AddressInputViewModel.cs
  src/FunderMaps.IndicentEndpoint/ViewModels/AddressOutputViewModel.cs
  src/FunderMaps.IndicentEndpoint/ViewModels/IncidentInputViewModel.cs
  src/FunderMaps.IndicentEndpoint/host.json
  tests/FunderMaps.IndicentEndpoint.Tests/FunderMaps.IndicentEndpoint.Tests.csproj
  tests/FunderMaps.IndicentEndpoint.Tests/HttpPortalEndpointTests.cs
Labels: enhancement

#275 Feature/review preparation
  src/FunderMaps.Core/Services/ProductService.cs
  src/FunderMaps.Core/Types/Distributions/ConstructionYearPair.cs
  src/FunderMaps.Core/Types/Distributions/FoundationTypePair.cs
  src/FunderMaps.Data/Extensions/DbDataReaderExtensions.cs
  src/FunderMaps.Data/Repositories/AnalysisRepository.cs
  src/FunderMaps.Data/Repositories/StatisticsRepository.cs
  src/FunderMaps.Webservice/Controllers/AuthController.cs
  src/FunderMaps.Webservice/Controllers/ErrorController.cs
  src/FunderMaps.Webservice/ResponseModels/Types/FoundationTypePairResponseModel.cs
  tests/FunderMaps.Testing/Faker/StatisticsProductFaker.cs
  tests/FunderMaps.Webservice.UnitTests/Mapping/AnalysisMappingTests.cs
  tests/FunderMaps.Webservice.UnitTests/Mapping/StatisticsMappingTests.cs
Labels: Webservice

#280 Removed checkIfAuthentaticated functionality
  src/FunderMaps.AspNetCore/Authentication/AuthenticationHelper.cs
  src/FunderMaps.Core.Authentication/AuthManager.cs
  src/FunderMaps.Infrastructure/FunderMaps.Infrastructure.csproj
  src/FunderMaps.WebApi/Controllers/Application/AuthController.cs
  src/FunderMaps.Webservice/FunderMaps.Webservice.csproj
  tests/FunderMaps.IntegrationTests/Backend/Application/OrganizationAdminTests.cs
  tests/FunderMaps.IntegrationTests/Backend/Application/OrganizationProposalTests.cs
  tests/FunderMaps.IntegrationTests/FunderMaps.IntegrationTests.csproj
  tests/FunderMaps.Testing/Extensions/BogusDataSetsExtensions.cs
  tests/FunderMaps.Testing/FunderMaps.Testing.csproj
Labels: enhancement

#289 Removed description service completely
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/Interfaces/IDescriptionService.cs
  src/FunderMaps.Core/Services/DescriptionService.cs
  src/FunderMaps.Core/Services/ProductService.cs
  src/FunderMaps.Core/Services/ProductTrackingService.cs
  src/FunderMaps.Core/Types/Products/AnalysisProduct.cs
  src/FunderMaps.Core/Types/Products/AnalysisProductType.cs
  src/FunderMaps.Data/Repositories/TrackingRepository.cs
  src/FunderMaps.Webservice/Helpers/ResponseModelTypeConverter.cs
  src/FunderMaps.Webservice/Mapping/AutoMapperProfile.cs
  src/FunderMaps.Webservice/Mapping/ProductTypeMapper.cs
  src/FunderMaps.Webservice/ResponseModels/Analysis/AnalysisBuildingDescriptionResponseModel.cs
  src/FunderMaps.Webservice/ResponseModels/Analysis/AnalysisCompleteResponseModel.cs
  src/FunderMaps.Webservice/ResponseModels/Analysis/AnalysisFoundationPlusResponseModel.cs
  src/FunderMaps.Webservice/ResponseModels/Analysis/AnalysisRiskResponseModel.cs
  src/FunderMaps.Webservice/ResponseModels/Types/AnalysisProductTypeResponseModel.cs
  src/FunderMaps.Webservice/Services/MappingService.cs
  tests/FunderMaps.IntegrationTests/Webservice/AnalysisTests.cs
  tests/FunderMaps.Testing/Faker/AnalysisProductFaker.cs
  tests/FunderMaps.Webservice.UnitTests/Mapping/AnalysisMappingTests.cs
  tests/FunderMaps.Webservice.UnitTests/Mapping/ProductTypeMapperTests.cs
Labels: enhancement

#281 Fixed incorrect injection of product tracing serivce
  src/FunderMaps.Webservice/Startup.cs
  tests/FunderMaps.IntegrationTests/Webservice/StartupTests.cs
Labels: enhancement

#283 Feature/geocoder building
  src/FunderMaps.Core/Entities/Address.cs
  src/FunderMaps.Core/Entities/Building.cs
  src/FunderMaps.Core/Types/BuildingType.cs
  src/FunderMaps.Core/UseCases/GeocoderUseCase.cs
  src/FunderMaps.Data/Repositories/AddressRepository.cs
  src/FunderMaps.Data/Repositories/BuildingRepository.cs
  src/FunderMaps.WebApi/Controllers/Portal/IncidentPortalController.cs
  src/FunderMaps.WebApi/DataTransferObjects/AddressBuildingDto.cs
  src/FunderMaps.WebApi/MapperProfile.cs
  src/FunderMaps.Webservice/FunderMaps.Webservice.csproj
  tests/FunderMaps.Core.Tests/Entities/AddressTests.cs
  tests/FunderMaps.Core.Tests/Entities/BuildingTests.cs
  tests/FunderMaps.Core.Tests/Mocks/MockBuildingRepository.cs
  tests/FunderMaps.Core.Tests/UseCases/GeocoderUseCaseTests.cs
  tests/FunderMaps.IntegrationTests/Backend/Portal/IncidentPortalTests.cs
  tests/FunderMaps.Testing/Faker/BuildingFaker.cs
  tests/FunderMaps.Testing/Repositories/TestBuildingRepository.cs
Labels: Feature, enhancement

#291 Feature/broom
  .github/workflows/dotnet-core-package-outdated.yml
  contrib/interface/FunderMaps.WebApi.postman_collection.json
  src/FunderMaps.AspNetCore/ErrorMessaging/CustomExceptionHandlerMiddleware.cs
  src/FunderMaps.AspNetCore/Extensions/CustomExceptionHandlerMiddlewareExtensions.cs
  src/FunderMaps.AspNetCore/FunderMapsExceptionMapper.cs
  src/FunderMaps.Core/Entities/Address.cs
  src/FunderMaps.Core/Entities/Application/IApplicationEntity.cs
  src/FunderMaps.Core/Entities/Contact.cs
  src/FunderMaps.Core/Entities/Geocoder/IGeocoderEntity.cs
  src/FunderMaps.Core/Entities/IInitializable.cs
  src/FunderMaps.Core/Entities/InquirySample.cs
  src/FunderMaps.Core/Entities/RecordControl.cs
  src/FunderMaps.Core/Entities/Recovery.cs
  src/FunderMaps.Core/Entities/RecoverySample.cs
  src/FunderMaps.Core/Entities/Report/IReportEntity.cs
  src/FunderMaps.Core/Entities/User.cs
  src/FunderMaps.Core/Interfaces/IErrorMessage.cs
  src/FunderMaps.Core/Interfaces/IExceptionMapper.cs
  src/FunderMaps.Core/Interfaces/Repositories/IOrganizationProposalRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/IOrganizationUserRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/IProjectSampleRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/IRecoveryRepository.cs
  src/FunderMaps.Core/Services/ExceptionMapperBase.cs
  src/FunderMaps.Core/Types/BaseMeasurementLevel.cs
  src/FunderMaps.Core/Types/Control/AccessControl.cs
  src/FunderMaps.Core/Types/Control/AttributionControl.cs
  src/FunderMaps.Core/Types/ErrorMessage.cs
  src/FunderMaps.Core/Types/Products/AnalysisProduct.cs
  src/FunderMaps.Core/Types/Products/AnalysisProductType.cs
  src/FunderMaps.Core/Types/Products/ProductBase.cs
  src/FunderMaps.Core/Types/Products/StatisticsProduct.cs
  src/FunderMaps.Core/Types/Products/StatisticsProductType.cs
  src/FunderMaps.Core/Types/WoodEncroachement.cs
  src/FunderMaps.Core/Types/WoodQuality.cs
  src/FunderMaps.Infrastructure/Storage/AzureBlobStorageService.cs
  src/FunderMaps.WebApi/Controllers/OopsController.cs
  src/FunderMaps.WebApi/DataTransferObjects/AddressBuildingDto.cs
  src/FunderMaps.WebApi/DataTransferObjects/AddressDto.cs
  src/FunderMaps.WebApi/DataTransferObjects/IncidentDto.cs
  src/FunderMaps.WebApi/DataTransferObjects/InquiryDto.cs
  src/FunderMaps.WebApi/DataTransferObjects/InquirySampleDto.cs
  src/FunderMaps.WebApi/DataTransferObjects/ProjectDto.cs
  src/FunderMaps.WebApi/DataTransferObjects/RecoveryDto.cs
  src/FunderMaps.WebApi/DataTransferObjects/RecoverySampleDto.cs
  src/FunderMaps.WebApi/Startup.cs
  src/FunderMaps.Webservice/Controllers/ErrorController.cs
  src/FunderMaps.Webservice/Startup.cs
  tests/FunderMaps.IntegrationTests/Backend/Portal/IncidentPortalTests.cs
  tests/FunderMaps.IntegrationTests/FileUploadContent.cs
  tests/FunderMaps.Webservice.UnitTests/Mapping/ProductTypeMapperTests.cs
Labels: enhancement

#296 Feature/zero rows
  src/FunderMaps.Data/Extensions/DbCommandExtensions.cs
  src/FunderMaps.Data/Repositories/AddressRepository.cs
  src/FunderMaps.Data/Repositories/ContactRepository.cs
  src/FunderMaps.Data/Repositories/IncidentRepository.cs
  src/FunderMaps.Data/Repositories/InquiryRepository.cs
  src/FunderMaps.Data/Repositories/InquirySampleRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationProposalRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationUserRepository.cs
  src/FunderMaps.Data/Repositories/RecoveryRepository.cs
  src/FunderMaps.Data/Repositories/RecoverySampleRepository.cs
  src/FunderMaps.Data/Repositories/UserRepository.cs
  src/FunderMaps.Infrastructure/FunderMaps.Infrastructure.csproj
Labels: bug

#298 Feature/hotfix
  src/FunderMaps.Core/DataAnnotations/ArrayEnumDataTypeAttribute.cs
  src/FunderMaps.Core/DataAnnotations/ArrayUrlAttribute.cs
  src/FunderMaps.Core/Entities/Contact.cs
  src/FunderMaps.Core/Entities/Incident.cs
  src/FunderMaps.Core/UseCases/IncidentUseCase.cs
  src/FunderMaps.WebApi/Controllers/Portal/IncidentPortalController.cs
  src/FunderMaps.WebApi/DataTransferObjects/IncidentDto.cs
  tests/FunderMaps.Core.Tests/UseCases/IncidentUseCaseTests.cs
  tests/FunderMaps.IntegrationTests/Backend/Portal/IncidentPortalTests.cs
  tests/FunderMaps.IntegrationTests/Webservice/StartupTests.cs
  tests/FunderMaps.Testing/Faker/IncidentDtoFaker.cs
Labels: Feature, enhancement

#302 Feature/contact email
  contrib/Laixer.TdmClient/Laixer.TdmClient.csproj
  src/FunderMaps.Core/Entities/BaseEntity.cs
  src/FunderMaps.Infrastructure/FunderMaps.Infrastructure.csproj
  src/FunderMaps.WebApi/DataTransferObjects/IncidentDto.cs
  src/FunderMaps.Webservice/FunderMaps.Webservice.csproj
Labels: bug, enhancement
