Repository Laixer/FunderMaps, pull requests merged in 2020-11, with the labels that each got.

#380 Rewrite notification hub
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/Interfaces/INotificationService.cs
  src/FunderMaps.Core/Interfaces/INotifyService.cs
  src/FunderMaps.Core/Notification/EmailHandler.cs
  src/FunderMaps.Core/Notification/Envelope.cs
  src/FunderMaps.Core/Notification/INotifyHandler.cs
  src/FunderMaps.Core/Notification/NotifyContext.cs
  src/FunderMaps.Core/Notification/NotifyContextStatus.cs
  src/FunderMaps.Core/Services/NotificationHub.cs
  src/FunderMaps.Core/Services/NullNotificationService.cs
  src/FunderMaps.Infrastructure/Extensions/FunderMapsInfrastructureServiceCollectionExtensions.cs
  src/FunderMaps.Infrastructure/Notification/NotificationHubService.cs
  src/FunderMaps.WebApi/Controllers/Report/InquiryController.cs
Labels: enhancement

#382 Feature/mvt tool
  FunderMaps.sln
  src/FunderMaps.BatchNode/Command/CommandInfo.cs
  src/FunderMaps.BatchNode/Command/CommandTask.cs
  src/FunderMaps.BatchNode/Command/CommandTaskContext.cs
  src/FunderMaps.BatchNode/Exceptions/ProtocolException.cs
  src/FunderMaps.BatchNode/Extensions/FunderMapsBatchWorkerServiceCollectionExtensions.cs
  src/FunderMaps.BatchNode/FunderMaps.BatchNode.csproj
  src/FunderMaps.BatchNode/GeoInterface/DataSource.cs
  src/FunderMaps.BatchNode/GeoInterface/FileDataSource.cs
  src/FunderMaps.BatchNode/GeoInterface/LayerSource.cs
  src/FunderMaps.BatchNode/GeoInterface/PostreSQLDataSource.cs
  src/FunderMaps.BatchNode/GeoInterface/SqlLayerSource.cs
  src/FunderMaps.BatchNode/GeoInterface/VectorDatasetBuilder.cs
  src/FunderMaps.BatchNode/GeoInterface/VectorDatasetBuilderOptions.cs
  src/FunderMaps.BatchNode/Jobs/BundleBuilder/BundleBuildingContext.cs
  src/FunderMaps.BatchNode/Jobs/BundleBuilder/BundleJob.cs
  src/FunderMaps.BatchNode/Jobs/BundleBuilder/BundleLayerSource.cs
  src/FunderMaps.BatchNode/Program.cs
  src/FunderMaps.BatchNode/Protos/batch.proto
  src/FunderMaps.BatchNode/Protos/protocol.proto
  src/FunderMaps.BatchNode/Services/BatchService.cs
  src/FunderMaps.BatchNode/Startup.cs
  src/FunderMaps.BatchNode/appsettings.json
  src/FunderMaps.Core/Entities/Bundle.cs
  src/FunderMaps.Core/Entities/Layer.cs
  src/FunderMaps.Core/Exceptions/ProcessException.cs
  src/FunderMaps.Core/Exceptions/QueueOverflowException.cs
  src/FunderMaps.Core/Exceptions/UnhandledTaskException.cs
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/Interfaces/IBlobStorageService.cs
  src/FunderMaps.Core/Interfaces/Repositories/IBundleRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/ILayerRepository.cs
  src/FunderMaps.Core/Services/NullBlobStorageService.cs
  src/FunderMaps.Core/Storage/StorageObject.cs
  src/FunderMaps.Core/Threading/BackgroundTask.cs
  src/FunderMaps.Core/Threading/BackgroundTaskContext.cs
  src/FunderMaps.Core/Threading/BackgroundWorkOptions.cs
  src/FunderMaps.Core/Threading/DispatchManager.cs
  src/FunderMaps.Core/Types/Bundle/BundleStatus.cs
  src/FunderMaps.Core/Types/Bundle/LayerColumnPair.cs
  src/FunderMaps.Core/Types/Bundle/LayerConfiguration.cs
  src/FunderMaps.Core/Types/GeometryExportFormat.cs
  src/FunderMaps.Data/Extensions/FunderMapsDataServiceCollectionExtensions.cs
  src/FunderMaps.Data/Providers/NpgsqlDbProvider.cs
  src/FunderMaps.Data/Repositories/BundleRepository.cs
  src/FunderMaps.Data/Repositories/IncidentRepository.cs
  src/FunderMaps.Data/Repositories/LayerRepository.cs
  src/FunderMaps.Infrastructure/Extensions/FunderMapsInfrastructureServiceCollectionExtensions.cs
  src/FunderMaps.Infrastructure/Storage/SpacesBlobStorageService.cs
Labels: console

#386 Feature/bundle api
  src/FunderMaps.Core/Entities/Bundle.cs
  src/FunderMaps.Core/Entities/Layer.cs
  src/FunderMaps.Core/Interfaces/Repositories/IBundleRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/ILayerRepository.cs
  src/FunderMaps.Data/Repositories/BundleRepository.cs
  src/FunderMaps.Data/Repositories/LayerRepository.cs
  src/FunderMaps.WebApi/Controllers/Report/BundleController.cs
  src/FunderMaps.WebApi/DataTransferObjects/BundleDto.cs
  src/FunderMaps.WebApi/MapperProfile.cs
Labels: Feature

#387 Feature/layer api
  contrib/interface/FunderMaps.WebApi.postman_collection.json
  src/FunderMaps.Core/Entities/Layer.cs
  src/FunderMaps.Data/Repositories/LayerRepository.cs
  src/FunderMaps.WebApi/Controllers/Maplayer/BundleController.cs
  src/FunderMaps.WebApi/Controllers/Maplayer/LayerController.cs
  src/FunderMaps.WebApi/DataTransferObjects/BundleDto.cs
  src/FunderMaps.WebApi/DataTransferObjects/LayerDto.cs
  src/FunderMaps.WebApi/MapperProfile.cs
Labels: Feature

#390 Feature/layer markup
  src/FunderMaps.Core/Entities/Layer.cs
  src/FunderMaps.Data/Repositories/LayerRepository.cs
  src/FunderMaps.WebApi/Controllers/Maplayer/LayerController.cs
  src/FunderMaps.WebApi/DataTransferObjects/LayerDto.cs
Labels: enhancement

#395 Feature/bundle batch
  src/FunderMaps.BatchNode/Jobs/BundleBuilder/BundleBatch.cs
  src/FunderMaps.BatchNode/Startup.cs
  src/FunderMaps.Data/Repositories/BundleRepository.cs
Labels: Feature

#396 Update BundleRepository.cs
  src/FunderMaps.Data/Repositories/BundleRepository.cs
Labels: bug

#397 Feature/html template
  src/FunderMaps.BatchNode/Jobs/BundleBuilder/BundleBatch.cs
  src/FunderMaps.BatchNode/Jobs/BundleBuilder/BundleJob.cs
  src/FunderMaps.BatchNode/Jobs/FooBarJob.cs
  src/FunderMaps.BatchNode/Jobs/IncidentNotifyJob.cs
  src/FunderMaps.BatchNode/Jobs/Notification/EmailJob.cs
  src/FunderMaps.BatchNode/Jobs/Notification/NotificationTask.cs
  src/FunderMaps.BatchNode/Startup.cs
  src/FunderMaps.Core/Components/TemplateParser.cs
  src/FunderMaps.Core/Email/EmailMessage.cs
  src/FunderMaps.Core/Entities/Address.cs
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/FunderMaps.Core.csproj
  src/FunderMaps.Core/Interfaces/ITemplateParser.cs
  src/FunderMaps.Core/Notification/Envelope.cs
  src/FunderMaps.Core/Notification/INotifyService.cs
  src/FunderMaps.Core/Notification/NotificationHub.cs
  src/FunderMaps.Core/Template/Email/incident.html
  src/FunderMaps.Core/Threading/DispatchManager.cs
  src/FunderMaps.Infrastructure/Email/EmailService.cs
  src/FunderMaps.Portal/Controllers/IncidentPortalController.cs
Labels: Feature

#399 Send NULL to db if value is nullable
  src/FunderMaps.Data/Repositories/ContactRepository.cs
  src/FunderMaps.Data/Repositories/IncidentRepository.cs
  src/FunderMaps.WebApi/Controllers/Report/IncidentController.cs
Labels: enhancement
