Repository Laixer/FunderMaps, pull requests merged in 2021-03, with the labels that each got.

#497 GeocoderTranslation service now throws 404 when an address id is not known
  src/FunderMaps.Core/Components/GeocoderTranslation.cs
Labels: bug

#495 Prevent AppContext scope race condition
  src/FunderMaps.AspNetCore/Components/AspAppContextFactory.cs
  src/FunderMaps.AspNetCore/Components/AspAppContextMiddleware.cs
  src/FunderMaps.AspNetCore/ErrorMessaging/CustomExceptionHandlerMiddleware.cs
  src/FunderMaps.AspNetCore/Extensions/AspAppContextMiddlewareExtensions.cs
  src/FunderMaps.AspNetCore/FunderMapsStartup.cs
  src/FunderMaps.Core/AppContext.cs
  src/FunderMaps.Core/Threading/DispatchManager.cs
  src/FunderMaps.Portal/Startup.cs
  src/FunderMaps.WebApi/Startup.cs
  src/FunderMaps.Webservice/Startup.cs
Labels: bug

#498 Feature/exception messages
  src/FunderMaps.AspNetCore/Controllers/OopsController.cs
  src/FunderMaps.AspNetCore/ErrorMessaging/CustomExceptionHandlerMiddleware.cs
  src/FunderMaps.AspNetCore/ErrorMessaging/CustomExceptionHandlerOptions.cs
  src/FunderMaps.AspNetCore/Extensions/CustomExceptionHandlerMiddlewareExtensions.cs
  src/FunderMaps.AspNetCore/Extensions/ExceptionMapperServiceCollectionExtensions.cs
  src/FunderMaps.AspNetCore/FunderMapsExceptionMapper.cs
  src/FunderMaps.AspNetCore/FunderMapsStartup.cs
  src/FunderMaps.Core/Components/GeocoderTranslation.cs
  src/FunderMaps.Core/Exceptions/AuthenticationException.cs
  src/FunderMaps.Core/Exceptions/AuthorizationException.cs
  src/FunderMaps.Core/Exceptions/EntityNotFoundException.cs
  src/FunderMaps.Core/Exceptions/EntityReadOnlyException.cs
  src/FunderMaps.Core/Exceptions/FunderMapsCoreException.cs
  src/FunderMaps.Core/Exceptions/InvalidCredentialException.cs
  src/FunderMaps.Core/Exceptions/InvalidIdentifierException.cs
  src/FunderMaps.Core/Exceptions/OperationAbortedException.cs
  src/FunderMaps.Core/Exceptions/ProcessException.cs
  src/FunderMaps.Core/Exceptions/QueueOverflowException.cs
  src/FunderMaps.Core/Exceptions/ReferenceNotFoundException.cs
  src/FunderMaps.Core/Exceptions/ServiceUnavailableException.cs
  src/FunderMaps.Core/Exceptions/StateTransitionException.cs
  src/FunderMaps.Core/Exceptions/StorageException.cs
  src/FunderMaps.Core/Exceptions/UnhandledTaskException.cs
  src/FunderMaps.Core/Interfaces/IExceptionMapper.cs
  src/FunderMaps.Core/Types/ErrorMessage.cs
  src/FunderMaps.Portal/Startup.cs
  src/FunderMaps.WebApi/Startup.cs
  src/FunderMaps.Webservice/Startup.cs
  tests/FunderMaps.IntegrationTests/ProblemModel.cs
Labels: enhancement

#514 Feature/ws imrpov
  database/fundermaps_base.sql
  database/fundermaps_permissions.sql
  src/FunderMaps.AspNetCore/DataTransferObjects/StatisticsDto.cs
  src/FunderMaps.AspNetCore/FunderMapsStartup.cs
  src/FunderMaps.Core/Interfaces/Repositories/IStatisticsRepository.cs
  src/FunderMaps.Core/Services/ProductService.cs
  src/FunderMaps.Core/Types/Distributions/FoundationTypeDistribution.cs
  src/FunderMaps.Core/Types/Distributions/IncidentYearPair.cs
  src/FunderMaps.Core/Types/Distributions/InquiryYearPair.cs
  src/FunderMaps.Core/Types/Products/StatisticsProduct.cs
  src/FunderMaps.Core/Types/Years.cs
  src/FunderMaps.Data/DbContext.cs
  src/FunderMaps.Data/Repositories/StatisticsRepository.cs
  tests/FunderMaps.IntegrationTests/Webservice/StatisticsTests.cs
  tests/FunderMaps.Testing/Faker/AddressFaker.cs
  tests/FunderMaps.Testing/Faker/AnalysisProductFaker.cs
  tests/FunderMaps.Testing/Faker/BuildingFaker.cs
  tests/FunderMaps.Testing/Faker/ContactFaker.cs
  tests/FunderMaps.Testing/Faker/IncidentFaker.cs
  tests/FunderMaps.Testing/Faker/InquiryFaker.cs
  tests/FunderMaps.Testing/Faker/InquirySampleFaker.cs
  tests/FunderMaps.Testing/Faker/OrganizationProposalFaker.cs
  tests/FunderMaps.Testing/Faker/ProjectFaker.cs
  tests/FunderMaps.Testing/Faker/ProjectSampleFaker.cs
  tests/FunderMaps.Testing/Faker/RecoveryFaker.cs
  tests/FunderMaps.Testing/Faker/RecoverySampleFaker.cs
  tests/FunderMaps.Testing/Faker/StatisticsProductFaker.cs
Labels: Feature

#524 Remove sorting
  src/FunderMaps.AspNetCore/DataTransferObjects/PaginationDto.cs
  src/FunderMaps.Core/Navigation.cs
  src/FunderMaps.Data/RepositoryBase.cs
Labels: Enhancement

#525 Remove building for project
  database/fundermaps_base.sql
  src/FunderMaps.AspNetCore/DataTransferObjects/AddressDto.cs
  src/FunderMaps.AspNetCore/FunderMapsStartup.cs
  src/FunderMaps.Core/Entities/Address.cs
  src/FunderMaps.Core/Entities/Building.cs
  src/FunderMaps.Core/Interfaces/Repositories/IBuildingRepository.cs
  src/FunderMaps.Data/Extensions/FunderMapsDataServiceCollectionExtensions.cs
  src/FunderMaps.Data/Repositories/AddressRepository.cs
  src/FunderMaps.Data/Repositories/BuildingRepository.cs
  src/FunderMaps.WebApi/Controllers/Geocoder/AddressController.cs
  tests/FunderMaps.IntegrationTests/Backend/Geocoder/AddressTests.cs
Labels: Enhancement

#532 v3.2.1
  database/data/seed_application.sql
  database/data/seed_report.sql
  database/fundermaps_base.sql
  src/FunderMaps.AspNetCore/Authentication/SignInService.cs
  src/FunderMaps.AspNetCore/DataTransferObjects/OrganizationDto.cs
  src/FunderMaps.Core/Entities/Organization.cs
  src/FunderMaps.Core/Entities/User.cs
  src/FunderMaps.Core/Exceptions/StateTransitionException.cs
  src/FunderMaps.Data/Repositories/AddressRepository.cs
  src/FunderMaps.Data/Repositories/BundleRepository.cs
  src/FunderMaps.Data/Repositories/ContactRepository.cs
  src/FunderMaps.Data/Repositories/IncidentRepository.cs
  src/FunderMaps.Data/Repositories/InquiryRepository.cs
  src/FunderMaps.Data/Repositories/InquirySampleRepository.cs
  src/FunderMaps.Data/Repositories/LayerRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationProposalRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationRepository.cs
  src/FunderMaps.Data/Repositories/RecoveryRepository.cs
  src/FunderMaps.Data/Repositories/RecoverySampleRepository.cs
  src/FunderMaps.Data/Repositories/UserRepository.cs
  src/FunderMaps.WebApi/Controllers/Application/ReviewerController.cs
  src/FunderMaps.WebApi/Controllers/Geocoder/AddressController.cs
  src/FunderMaps.WebApi/Controllers/Maplayer/BundleController.cs
  src/FunderMaps.WebApi/Controllers/Maplayer/LayerController.cs
  src/FunderMaps.WebApi/Controllers/Report/InquiryController.cs
  src/FunderMaps.WebApi/DataTransferObjects/InquiryDto.cs
  tests/FunderMaps.IntegrationTests/Backend/Application/OrganizationTests.cs
  tests/FunderMaps.IntegrationTests/Backend/Report/InquiryTests.cs
  tests/FunderMaps.Testing/Faker/OrganizationDtoFaker.cs
  tests/FunderMaps.Testing/Faker/OrganizationFaker.cs
  tests/FunderMaps.Testing/Faker/UserFaker.cs
Labels: Release
