Repository Laixer/FunderMaps, pull requests merged in 2021-02, with the labels that each got.

#443 Feature/incident portal
  src/FunderMaps.AspNetCore/DataTransferObjects/IncidentDto.cs
  src/FunderMaps.Core/Components/GeocoderTranslation.cs
  src/FunderMaps.Core/Entities/Incident.cs
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/Interfaces/IGeocoderTranslation.cs
  src/FunderMaps.Core/Interfaces/IIncidentService.cs
  src/FunderMaps.Core/Interfaces/Repositories/IAddressRepository.cs
  src/FunderMaps.Core/Services/IncidentService.cs
  src/FunderMaps.Portal/Controllers/IncidentPortalController.cs
  src/FunderMaps.WebApi/Controllers/Report/IncidentController.cs
  tests/FunderMaps.IntegrationTests/Backend/Geocoder/AddressTests.cs
  tests/FunderMaps.IntegrationTests/Backend/Report/IncidentTests.cs
  tests/FunderMaps.IntegrationTests/Portal/IncidentPortalTests.cs
Labels: enhancement

#446 Feature/incident
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/IncidentReport/IIncidentService.cs
  src/FunderMaps.Core/IncidentReport/IncidentOptions.cs
  src/FunderMaps.Core/IncidentReport/IncidentService.cs
  src/FunderMaps.Core/Threading/BackgroundTaskContext.cs
  src/FunderMaps.Portal/Controllers/IncidentPortalController.cs
  src/FunderMaps.WebApi/Controllers/Report/IncidentController.cs
Labels: enhancement

#447 Remove the ref
  src/FunderMaps.Data/Repositories/AddressRepository.cs
  src/FunderMaps.Data/Repositories/BundleRepository.cs
  src/FunderMaps.Data/Repositories/ContactRepository.cs
  src/FunderMaps.Data/Repositories/IncidentRepository.cs
  src/FunderMaps.Data/Repositories/InquiryRepository.cs
  src/FunderMaps.Data/Repositories/InquirySampleRepository.cs
  src/FunderMaps.Data/Repositories/LayerRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationProposalRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationRepository.cs
  src/FunderMaps.Data/Repositories/RecoveryRepository.cs
  src/FunderMaps.Data/Repositories/RecoverySampleRepository.cs
  src/FunderMaps.Data/Repositories/UserRepository.cs
  src/FunderMaps.Data/RepositoryBase.cs
Labels: enhancement

#448 Feature/notify hub
  src/FunderMaps.AspNetCore/HealthChecks/EmailHealthCheck.cs
  src/FunderMaps.BatchNode/Extensions/FunderMapsBatchWorkerServiceCollectionExtensions.cs
  src/FunderMaps.BatchNode/Jobs/IncidentNotifyJob.cs
  src/FunderMaps.BatchNode/Startup.cs
  src/FunderMaps.Core/Components/TemplateParser.cs
  src/FunderMaps.Core/Email/EmailAddress.cs
  src/FunderMaps.Core/Email/IEmailService.cs
  src/FunderMaps.Core/Email/NullEmailService.cs
  src/FunderMaps.Core/Entities/Incident.cs
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/IncidentReport/IncidentService.cs
  src/FunderMaps.Core/Interfaces/ITemplateParser.cs
  src/FunderMaps.Core/Notification/Envelope.cs
  src/FunderMaps.Core/Notification/INotifyService.cs
  src/FunderMaps.Core/Notification/Jobs/EmailJob.cs
  src/FunderMaps.Core/Notification/NotificationHub.cs
  src/FunderMaps.Core/Notification/NotificationJob.cs
  src/FunderMaps.Core/Threading/BackgroundTask.cs
  src/FunderMaps.Core/Threading/FooBarJob.cs
  src/FunderMaps.Infrastructure/Email/SmtpOptions.cs
  src/FunderMaps.Infrastructure/Email/SmtpService.cs
  src/FunderMaps.Infrastructure/Extensions/FunderMapsInfrastructureServiceCollectionExtensions.cs
  src/FunderMaps.Portal/Controllers/IncidentPortalController.cs
  src/FunderMaps.WebApi/Controllers/Report/InquiryController.cs
Labels: enhancement

#449 Feature/appcontext
  src/FunderMaps.AspNetCore/Components/AspAppContextFactory.cs
  src/FunderMaps.Core/AppContext.cs
  src/FunderMaps.Portal/Constants.cs
  src/FunderMaps.Portal/Controllers/IncidentPortalController.cs
  src/FunderMaps.WebApi/Constants.cs
  src/FunderMaps.WebApi/Controllers/Report/IncidentController.cs
Labels: enhancement

#451 Feature/smtp
  .github/workflows/dotnet-core.yml
  contrib/etc/_appsettings.Development.json
  contrib/etc/_appsettings.Production.json
  contrib/etc/_appsettings.Staging.json
  src/FunderMaps.BatchNode/appsettings.json
  src/FunderMaps.Core/Email/IEmailService.cs
  src/FunderMaps.Core/Email/NullEmailService.cs
  src/FunderMaps.Core/Notification/Jobs/EmailJob.cs
  src/FunderMaps.Infrastructure/Email/SmtpOptions.cs
  src/FunderMaps.Infrastructure/Email/SmtpService.cs
  src/FunderMaps.Portal/appsettings.json
  src/FunderMaps.WebApi/appsettings.json
  src/FunderMaps.Webservice/appsettings.json
Labels: enhancement

#453 Feature/isolate batchnode
  .vscode/launch.json
  Dockerfile
  src/FunderMaps.BatchNode/Exceptions/ProtocolException.cs
  src/FunderMaps.BatchNode/FunderMaps.BatchNode.csproj
  src/FunderMaps.BatchNode/GeoInterface/DataSource.cs
  src/FunderMaps.BatchNode/GeoInterface/PostreSQLDataSource.cs
  src/FunderMaps.BatchNode/GrpcAppContextFactory.cs
  src/FunderMaps.BatchNode/Jobs/BundleBuilder/BundleBatch.cs
  src/FunderMaps.BatchNode/Jobs/BundleBuilder/BundleBuildingContext.cs
  src/FunderMaps.BatchNode/Program.cs
  src/FunderMaps.BatchNode/Services/BatchService.cs
  src/FunderMaps.BatchNode/Services/TimedHostedService.cs
  src/FunderMaps.BatchNode/Startup.cs
  src/FunderMaps.BatchNode/TimedHostedService.cs
  src/FunderMaps.Cli/Drivers/BatchDriver.cs
  src/FunderMaps.Core/Abstractions/AppServiceBase.cs
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/FunderMaps.Core.csproj
  src/FunderMaps.Core/IncidentReport/IncidentService.cs
  src/FunderMaps.Core/Interfaces/Repositories/IBundleRepository.cs
  src/FunderMaps.Core/MapBundle/BundleBuildingContext.cs
  src/FunderMaps.Core/MapBundle/BundleHub.cs
  src/FunderMaps.Core/MapBundle/BundleLayerSource.cs
  src/FunderMaps.Core/MapBundle/DataSource.cs
  src/FunderMaps.Core/MapBundle/FileDataSource.cs
  src/FunderMaps.Core/MapBundle/IBundleService.cs
  src/FunderMaps.Core/MapBundle/Jobs/BundleJob.cs
  src/FunderMaps.Core/MapBundle/LayerSource.cs
  src/FunderMaps.Core/MapBundle/PostreSQLDataSource.cs
  src/FunderMaps.Core/MapBundle/SqlLayerSource.cs
  src/FunderMaps.Core/MapBundle/VectorDatasetBuilder.cs
  src/FunderMaps.Core/MapBundle/VectorDatasetBuilderOptions.cs
  src/FunderMaps.Core/Notification/NotificationHub.cs
  src/FunderMaps.Core/Threading/Command/CommandInfo.cs
  src/FunderMaps.Core/Threading/Command/CommandTask.cs
  src/FunderMaps.Core/Threading/Command/CommandTaskContext.cs
  src/FunderMaps.Data/Repositories/BundleRepository.cs
  src/FunderMaps.Infrastructure/BatchClient/BatchOptions.cs
  src/FunderMaps.Infrastructure/BatchClient/BatchProxy.cs
  src/FunderMaps.Infrastructure/BatchClient/ChannelFactory.cs
  src/FunderMaps.Infrastructure/BatchClient/Protocol.cs
  src/FunderMaps.Infrastructure/Extensions/FunderMapsInfrastructureServiceCollectionExtensions.cs
  src/FunderMaps.Infrastructure/FunderMaps.Infrastructure.csproj
Labels: enhancement

#456 Feature/sweep
  src/FunderMaps.AspNetCore/DataTransferObjects/AddressSearchDto.cs
  src/FunderMaps.AspNetCore/DataTransferObjects/PaginationDto.cs
  src/FunderMaps.AspNetCore/InputModels/PaginationInputModel.cs
  src/FunderMaps.Core/Extensions/NavigationExtensions.cs
  src/FunderMaps.Core/Interfaces/INavigation.cs
  src/FunderMaps.Core/Interfaces/Repositories/IAddressRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/IAsyncRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/IBundleRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/IInquirySampleRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/IOrganizationUserRepository.cs
  src/FunderMaps.Core/MapBundle/BundleHub.cs
  src/FunderMaps.Core/Navigation.cs
  src/FunderMaps.Data/Repositories/AddressRepository.cs
  src/FunderMaps.Data/Repositories/BuildingRepository.cs
  src/FunderMaps.Data/Repositories/BundleRepository.cs
  src/FunderMaps.Data/Repositories/ContactRepository.cs
  src/FunderMaps.Data/Repositories/IncidentRepository.cs
  src/FunderMaps.Data/Repositories/InquiryRepository.cs
  src/FunderMaps.Data/Repositories/InquirySampleRepository.cs
  src/FunderMaps.Data/Repositories/LayerRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationProposalRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationRepository.cs
  src/FunderMaps.Data/Repositories/OrganizationUserRepository.cs
  src/FunderMaps.Data/Repositories/RecoveryRepository.cs
  src/FunderMaps.Data/Repositories/RecoverySampleRepository.cs
  src/FunderMaps.Data/Repositories/UserRepository.cs
  src/FunderMaps.Data/RepositoryBase.cs
  src/FunderMaps.Infrastructure/FunderMaps.Infrastructure.csproj
  src/FunderMaps.Infrastructure/Protos/batch.proto
  src/FunderMaps.Infrastructure/Protos/protocol.proto
  src/FunderMaps.Webservice/InputModels/AnalysisInputModel.cs
  tests/FunderMaps.IntegrationTests/FunderMaps.IntegrationTests.csproj
  tests/FunderMaps.Testing/FunderMaps.Testing.csproj
  tests/FunderMaps.Testing/Helper.cs
  tests/FunderMaps.Testing/Repositories/TestAddressRepository.cs
  tests/FunderMaps.Testing/Repositories/TestInquirySampleRepository.cs
  tests/FunderMaps.Testing/Repositories/TestOrganizationUserRepository.cs
  tests/FunderMaps.Testing/Repositories/TestRepositoryBase.cs
  tests/FunderMaps.Testing/Repositories/TestUserRepository.cs
Labels: enhancement

#455 Split/rewrite email templates and add applicationDirectory to AppContext
  src/FunderMaps.Core/AppContext.cs
  src/FunderMaps.Core/Components/TemplateParser.cs
  src/FunderMaps.Core/FunderMaps.Core.csproj
  src/FunderMaps.Core/Template/Email/Footer.html
  src/FunderMaps.Core/Template/Email/Header.html
  src/FunderMaps.Core/Template/Email/incident.html
Labels: enhancement

#458 Remove traces of geocoder
  src/FunderMaps.AspNetCore/DataTransferObjects/AddressSearchDto.cs
  src/FunderMaps.Core/Entities/Address.cs
  src/FunderMaps.Core/Interfaces/Repositories/IAddressRepository.cs
  src/FunderMaps.Data/Repositories/AddressRepository.cs
  src/FunderMaps.WebApi/Controllers/Geocoder/AddressController.cs
  tests/FunderMaps.IntegrationTests/Backend/Geocoder/AddressTests.cs
  tests/FunderMaps.Testing/Repositories/TestAddressRepository.cs
Labels: enhancement

#460 Make built_year nullable for inquiry samples
  src/FunderMaps.Core/Entities/InquirySample.cs
  src/FunderMaps.Data/Repositories/InquirySampleRepository.cs
  src/FunderMaps.WebApi/DataTransferObjects/InquirySampleDto.cs
Labels: bug

#459 Feature/email update
  src/FunderMaps.Core/Entities/User.cs
  src/FunderMaps.Core/IncidentReport/IncidentService.cs
  src/FunderMaps.Core/Notification/INotifyService.cs
  src/FunderMaps.Core/Notification/NotificationHub.cs
  src/FunderMaps.Core/Template/Email/Footer.html
  src/FunderMaps.Core/Template/Email/Header.html
  src/FunderMaps.Core/Template/Email/Incident.html
  src/FunderMaps.Core/Template/Email/InquiryApproved.html
  src/FunderMaps.Core/Template/Email/InquiryRejected.html
  src/FunderMaps.Core/Template/Email/InquiryReview.html
  src/FunderMaps.WebApi/Controllers/Report/InquiryController.cs
  tests/FunderMaps.IntegrationTests/Backend/Report/InquiryTests.cs
Labels: Feature, enhancement

#465 Remove the batch service client
  src/FunderMaps.AspNetCore/FunderMapsStartup.cs
  src/FunderMaps.AspNetCore/HealthChecks/BatchHealthCheck.cs
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/Interfaces/IBatchService.cs
  src/FunderMaps.Core/Services/NullBatchService.cs
Labels: enhancement

#469 Feature/geocoder clientapp
  src/FunderMaps.Core/Entities/InquirySample.cs
  src/FunderMaps.WebApi/Controllers/Geocoder/AddressController.cs
  src/FunderMaps.WebApi/Controllers/Report/InquirySampleController.cs
  src/FunderMaps.WebApi/DataTransferObjects/InquirySampleDto.cs
  tests/FunderMaps.IntegrationTests/Backend/Report/InquirySampleTests.cs
Labels: enhancement

#476 v3.1-prerelease
  src/FunderMaps.AspNetCore/FunderMapsStartup.cs
  src/FunderMaps.AspNetCore/HealthChecks/BatchHealthCheck.cs
  src/FunderMaps.Core/Entities/InquirySample.cs
  src/FunderMaps.Core/Extensions/FunderMapsCoreServiceCollectionExtensions.cs
  src/FunderMaps.Core/Interfaces/IBatchService.cs
  src/FunderMaps.Core/MapBundle/BundleHub.cs
  src/FunderMaps.Core/Services/NullBatchService.cs
  src/FunderMaps.Data/Repositories/BundleRepository.cs
  src/FunderMaps.WebApi/Controllers/Geocoder/AddressController.cs
  src/FunderMaps.WebApi/Controllers/Report/InquirySampleController.cs
  src/FunderMaps.WebApi/DataTransferObjects/InquirySampleDto.cs
  tests/FunderMaps.IntegrationTests/Backend/Report/InquirySampleTests.cs
Labels: release

#485 Feature/batch tuning
  contrib/etc/_appsettings.Development.json
  contrib/etc/_appsettings.Production.json
  contrib/etc/_appsettings.Staging.json
  src/FunderMaps.BatchNode/TimedHostedService.cs
  src/FunderMaps.Core/MapBundle/BundleHub.cs
  src/FunderMaps.Core/MapBundle/Jobs/BundleJob.cs
  src/FunderMaps.Core/Threading/BackgroundWorkOptions.cs
  src/FunderMaps.Core/Threading/Command/CommandTask.cs
  src/FunderMaps.Core/Threading/DispatchManager.cs
Labels: enhancement

#490 Feature/inquiry sample expansion
  src/FunderMaps.Core/Entities/InquirySample.cs
  src/FunderMaps.Core/Types/BaseMeasurementLevel.cs
  src/FunderMaps.Core/Types/FoundationDamageCause.cs
  src/FunderMaps.Core/Types/FoundationType.cs
  src/FunderMaps.Data/Providers/NpgsqlDbProvider.cs
  src/FunderMaps.Data/Repositories/InquirySampleRepository.cs
  src/FunderMaps.WebApi/DataTransferObjects/InquirySampleDto.cs
  tests/FunderMaps.Testing/Faker/InquirySampleDtoFaker.cs
  tests/FunderMaps.Testing/Faker/InquirySampleFaker.cs
Labels: enhancement

#491 Feature/batch improve
  src/FunderMaps.Core/Threading/Command/CommandTask.cs
  src/FunderMaps.Core/Threading/DispatchManager.cs
  src/FunderMaps.Core/Threading/DispatchManagerStatus.cs
Labels: enhancement

#480 Implement recovery features
  contrib/interface/FunderMaps.WebApi.postman_collection.json
  src/FunderMaps.Core/Constants.cs
  src/FunderMaps.Core/Entities/Recovery.cs
  src/FunderMaps.Core/Entities/RecoverySample.cs
  src/FunderMaps.Core/Interfaces/Repositories/IRecoveryRepository.cs
  src/FunderMaps.Core/Interfaces/Repositories/IRecoverySampleRepository.cs
  src/FunderMaps.Core/Template/Email/RecoveryApproved.html
  src/FunderMaps.Core/Template/Email/RecoveryRejected.html
  src/FunderMaps.Core/Template/Email/RecoveryReview.html
  src/FunderMaps.Data/Repositories/RecoveryRepository.cs
  src/FunderMaps.Data/Repositories/RecoverySampleRepository.cs
  src/FunderMaps.WebApi/Controllers/Report/RecoveryController.cs
  src/FunderMaps.WebApi/Controllers/Report/RecoverySampleController.cs
  src/FunderMaps.WebApi/DataTransferObjects/RecoveryDto.cs
  src/FunderMaps.WebApi/MapperProfile.cs
  tests/FunderMaps.Testing/Faker/RecoveryFaker.cs
  tests/FunderMaps.Testing/Repositories/TestRecoveryRepository.cs
  tests/FunderMaps.Testing/Repositories/TestRecoverySampleRepository.cs
Labels: Feature
