Repository Laixer/FunderMaps, pull requests merged in 2021-01, with the labels that each got.

#425 Change BuildingType enum and add entry to db enum mapper
  src/FunderMaps.Core/Types/BuildingType.cs
  src/FunderMaps.Data/Providers/NpgsqlDbProvider.cs
  tests/FunderMaps.Core.Tests/Entities/BuildingTests.cs
Labels: bug

#428 Feature/email service
  src/FunderMaps.AspNetCore/FunderMaps.AspNetCore.csproj
  src/FunderMaps.Core/FunderMaps.Core.csproj
  src/FunderMaps.Infrastructure/Email/EmailService.cs
  src/FunderMaps.Infrastructure/FunderMaps.Infrastructure.csproj
  tests/FunderMaps.Core.Tests/FunderMaps.Core.Tests.csproj
  tests/FunderMaps.IntegrationTests/FunderMaps.IntegrationTests.csproj
Labels: bug

#430 Feature/docker
  .github/workflows/dotnet-core-docker.yml
  Dockerfile
  Makefile
Labels: enhancement

#442 v2.9.4
  .github/workflows/dotnet-core-docker.yml
  Dockerfile
  Makefile
  src/FunderMaps.AspNetCore/DataTransferObjects/AnalysisDto.cs
  src/FunderMaps.AspNetCore/DataTransferObjects/AnalysisRiskPlusDto.cs
  src/FunderMaps.Core/FunderMaps.Core.csproj
  src/FunderMaps.Core/Types/BuiltYearSource.cs
  src/FunderMaps.Core/Types/Products/AnalysisProduct.cs
  src/FunderMaps.Data/FunderMaps.Data.csproj
  src/FunderMaps.Data/Providers/NpgsqlDbProvider.cs
  src/FunderMaps.Data/Repositories/AnalysisRepository.cs
  src/FunderMaps.Infrastructure/FunderMaps.Infrastructure.csproj
Labels: release
